### ISSUE TITLE
Missing Classes

### ISSUE THREAD

**Issue by xarly** [sghaida/ADWS#1]
Hi! Thanks for your work, it's promising!

I have downloaded your code to play a bit with it, but there are several classes missing or referenced but not present :/

ADGroupRequest
ADMoveObjectRequest
ADObjectTypecs
ADRenameRequest
CreateGroupRequest

Are you working on them?

Thanks!

**Comment by sghaida** [comment]
Hello, 

i updated the repo because i renamed some classes, you can check it out now and tell me if there is any problems.

thank you 
Saddam

**Comment by sghaida** [comment]
hello xarly,
would you like to contribute to this project?
Regards 
Saddam
